import random
from pathlib import Path

random.seed(42)

COUNTRIES = {
    "US": {
        "lang": "en",
        "categories": [
            ("NFL TEAMS", ["COWBOYS","PACKERS","PATRIOTS","EAGLES","GIANTS","BEARS","RAIDERS","BRONCOS","BILLS","CHIEFS","RAVENS","VIKINGS"]),
            ("NBA TEAMS", ["LAKERS","CELTICS","BULLS","KNICKS","HEAT","SPURS","SUNS","PISTONS","JAZZ","NETS","ROCKETS","WARRIORS"]),
            ("MLB TEAMS", ["YANKEES","METS","DODGERS","CUBS","REDSOX","GIANTS","PADRES","BRAVES","ASTROS","MARLINS","ORIOLES","CARDINALS"]),
            ("NHL TEAMS", ["RANGERS","BRUINS","KINGS","DUCKS","OILERS","FLAMES","PANTHERS","LIGHTNING","ISLANDERS","SHARKS","DEVILS","WILD"]),
            ("US SPORTS TV", ["ESPN","FOX","NBC","CBS","TNT","ABC","FS1","NFLN","MLBN","NBATV","PEACOCK","PRIME"]),
            ("US STADIUM WORDS", ["BLEACHERS","ENDZONE","BULLPEN","BASELINE","MIDCOURT","PITLANE","INFIELD","OUTFIELD","FACEOFF","HASHMARK","SIDELINE","DUGOUT"]),
            ("US COLLEGE POWERS", ["ALABAMA","GEORGIA","MICHIGAN","TEXAS","OHIOSTATE","CLEMSON","LSU","AUBURN","OREGON","FLORIDA","NOTREDAME","OKLAHOMA"]),
            ("US SPORTSWEAR", ["NIKE","REEBOK","WILSON","SPALDING","RAWLINGS","EASTON","UNDERARMOUR","NEWBALANCE","BROOKS","HOKA","JORDAN","TITLEIST"]),
            ("US LEGEND ATHLETES", ["JORDAN","BRADY","RUTH","ALI","KOBE","LEBRON","SERENA","PHELPS","WOODS","MONTANA","MANNING","BIRD"]),
            ("US OLYMPIC SPORTS", ["SWIMMING","GYMNASTICS","ATHLETICS","WRESTLING","BOXING","ROWING","FENCING","DIVING","SKATING","ARCHERY","CYCLING","VOLLEYBALL"]),
            ("US MOTORSPORT", ["NASCAR","INDYCAR","DAYTONA","TALLADEGA","PITSTOP","DRAFTING","POLE","LAPS","OVAL","FLAGMAN","CAUTION","SPOILER"]),
            ("US BASEBALL TERMS", ["HOMERUN","STRIKEOUT","FASTBALL","CURVEBALL","SLIDER","STEAL","BUNT","SACRIFICE","CATCHER","SHORTSTOP","PITCHER","WALKOFF"]),
            ("US BASKETBALL TERMS", ["DUNK","LAYUP","REBOUND","ASSIST","TURNOVER","BLOCK","STEAL","DRIBBLE","PICK","SCREEN","FADEAWAY","JUMPER"]),
            ("US FOOTBALL TERMS", ["TOUCHDOWN","FIELDGOAL","SACK","FUMBLE","SNAP","PUNT","BLITZ","AUDIBLE","RUSHING","RECEIVER","QUARTERBACK","LINEBACKER"]),
            ("US HOCKEY TERMS", ["PUCK","SLAPSHOT","ICING","POWERPLAY","CHECK","GOALIE","OFFSIDE","PENALTY","CREASE","BOARDS","FACEOFF","WRISTER"]),
            ("US TENNIS EVENTS", ["USOPEN","WIMBLEDON","ROLANDGARROS","AUSTRALIANOPEN","ACES","SERVE","VOLLEY","BACKHAND","FOREHAND","TIEBREAK","DEUCE","LOB"]),
            ("US FAN CULTURE", ["TAILGATE","MASCOT","HALFTIME","CHEER","CHANT","JERSEY","SEASONPASS","PLAYOFFS","RIVALRY","ROADTRIP","HOMETOWN","TROPHY"]),
            ("US BIG EVENTS", ["SUPERBOWL","WORLDSERIES","FINALS","STANLEYCUP","MASTERS","KENTUCKY","PREAKNESS","BELMONT","MARCHMADNESS","ALLSTAR","PROBOWL","DRAFT"]),
            ("US FIGHT SPORTS", ["UFC","BELLATOR","WELTERWEIGHT","HEAVYWEIGHT","OCTAGON","KNOCKOUT","SUBMISSION","ROUND","REFEREE","CUTMAN","CARDIO","SPARRING"]),
            ("US SPORTS CITIES", ["BOSTON","CHICAGO","DALLAS","MIAMI","SEATTLE","ATLANTA","DENVER","PHOENIX","DETROIT","HOUSTON","MINNEAPOLIS","PORTLAND"]),
        ],
    },
    "UK": {
        "lang": "en",
        "categories": [
            ("PREMIER CLUBS", ["ARSENAL","CHELSEA","LIVERPOOL","EVERTON","TOTTENHAM","UNITED","CITY","PALACE","FULHAM","WOLVES","WESTHAM","VILLA"]),
            ("UK FOOTBALL GROUNDS", ["ANFIELD","WEMBLEY","ETIHAD","STAMFORD","EMIRATES","OLDTRAFFORD","SELHURST","CRAVEN","GOODISON","IBROX","HAMPDEN","ELLAND"]),
            ("CRICKET TERMS", ["WICKET","BOWLER","BATSMAN","OVERS","MAIDEN","YORKER","SPIN","SEAM","CREASE","SLOGGER","LBW","GOOGLY"]),
            ("UK CRICKET VENUES", ["LORDS","OVAL","HEADINGLEY","TRENTBRIDGE","EDGBASTON","ROSEBOWL","CHESTERLE","TAUNTON","CARDIFF","OLDTRAFFORD","HOVE","BRISTOL"]),
            ("RUGBY NATIONS", ["ENGLAND","WALES","SCOTLAND","IRELAND","FRANCE","ITALY","FIJI","SAMOA","TONGA","JAPAN","ARGENTINA","AUSTRALIA"]),
            ("RUGBY TERMS", ["TRY","SCRUM","LINEOUT","RUCK","MAUL","CONVERSION","PENALTY","KNOCKON","OFFLOAD","PROP","FLANKER","HOOKER"]),
            ("UK TENNIS", ["WIMBLEDON","QUEENS","GRASS","SEEDING","CENTRECOURT","SERVE","RALLY","SLICE","TOPSPIN","TIEBREAK","QUALIFYING","BALLBOY"]),
            ("UK MOTORSPORT", ["SILVERSTONE","BRANDS","DONINGTON","GOODWOOD","FORMULAONE","POLE","CHICANE","DRS","DOWNFORCE","PITWALL","SAFETYCAR","PARCFERME"]),
            ("DARTS TERMS", ["BULLSEYE","TREBLE","DOUBLE","CHECKOUT","LEG","SET","OCHRE","NINEDARTER","THROWLINE","FINS","SHAFT","FLIGHT"]),
            ("SNOOKER TERMS", ["CUE","BREAK","POT","SNOOKER","FRAME","BAIZE","BLACKBALL","CENTURY","REST","SAFETY","CUSHION","POCKET"]),
            ("UK BOXING", ["RINGWALK","JAB","UPPERCUT","SOUTHPAW","ORTHODOX","TITLEFIGHT","PROMOTER","WEIGHIN","CORNER","CLINCH","COUNTER","CUT"]),
            ("UK SPORTS MEDIA", ["SKY","BTSPORT","BBC","ITV","TNT","TALKSport","ATHLETIC","GUARDIAN","TIMES","TELEGRAPH","MOTD","RADIOTWO"]),
            ("UK HORSE RACING", ["ASCOT","EPSOM","CHELTENHAM","AINTREE","NEWMARKET","JOCKEY","FURLONG","HANDICAP","STAKES","GALLOP","SADDLE","FINISHPOST"]),
            ("UK OLYMPIANS", ["FARAH","ENNIS","MURRAY","HOY","ADLINGTON","PEATY","WHITLOCK","WIGGINS","FROOME","THOMPSON","REDFERN","HEMMINGS"]),
            ("UK SPORTS CITIES", ["LONDON","MANCHESTER","LIVERPOOL","BIRMINGHAM","LEEDS","NEWCASTLE","GLASGOW","EDINBURGH","CARDIFF","BRISTOL","NOTTINGHAM","SHEFFIELD"]),
            ("FOOTBALL POSITIONS", ["GOALKEEPER","DEFENDER","MIDFIELDER","STRIKER","WINGER","FULLBACK","SWEEPER","PIVOT","PLAYMAKER","STOPPER","LIBERO","CAPTAIN"]),
            ("FOOTBALL ACTIONS", ["TACKLE","CROSS","HEADER","VOLLEY","PASS","DRIBBLE","CLEARANCE","THROUGHBALL","NUTMEG","PRESSING","MARKING","COUNTER"]),
            ("UK FAN CULTURE", ["DERBY","AWAYDAY","CHIPPY","SCARF","CHANT","ULTRAS","TERRACE","TURNSTILE","FIXTURE","RELEGATION","PROMOTION","CUPTIE"]),
            ("UK SWIMMING", ["FREESTYLE","BACKSTROKE","BREASTSTROKE","BUTTERFLY","HEATS","LANE","MEDLEY","SPLIT","TOUCHPAD","STARTER","WHISTLE","RELAY"]),
            ("UK CYCLING", ["PELOTON","SPRINT","CLIMB","TIME_TRIAL","DOMESTIQUE","BREAKAWAY","CADENCE","CHAINRING","PINNACLE","BIDON","DESCENT","STAGE"]),
        ],
    },
    "MX": {
        "lang": "es",
        "categories": [
            ("CLUBES LIGA MX", ["AMERICA","CHIVAS","PUMAS","CRUZAZUL","TIGRES","RAYADOS","TOLUCA","PACHUCA","SANTOS","NECAXA","ATLAS","LEON"]),
            ("ESTADIOS MEXICO", ["AZTECA","BBVA","OLIMPICO","JALISCO","CUAUHTEMOC","NEMESIO","CORREGIDORA","TERRITORIO","UNIVERSITARIO","VICTORIA","AKRON","HIDALGO"]),
            ("SELECCION MEXICO", ["TRICOLOR","PORTERO","DEFENSA","MEDIOCAMPO","DELANTERO","CAPITAN","CONCACAF","ELIMINATORIA","MUNDIAL","AMISTOSO","AFICION","CAMISETA"]),
            ("BEISBOL MEXICANO", ["DIABLOS","SULTANES","TIGRES","SARAPEROS","ACEREROS","PERICOS","BRAVOS","YAQUIS","NARANJEROS","VENADOS","ALGODONEROS","TOMATEROS"]),
            ("LIGA DEL PACIFICO", ["HERMOSILLO","CULIACAN","MEXICALI","MAZATLAN","GUASAVE","OBREGON","MOCHIS","NAYARIT","PITCHEO","NOVENAS","PLAYOFF","SERIE"]),
            ("LUCHA LIBRE", ["RUDO","TECNICO","ENMASCARADO","LLAVE","CASTIGO","LONA","APLAUSO","ARENA","RELEVOS","CAIDA","TOPE","PLANCHA"]),
            ("LUCHADORES ICONICOS", ["SANTO","BLUEDEMON","MILMASCARAS","MISTICO","ULTIMOGUERRERO","PSICOSIS","LA_PARKA","RUSH","PENTAGON","FENIX","VOLADOR","HECHICERO"]),
            ("BOXEO MEXICANO", ["CANELO","CHAVEZ","MORALES","BARRERA","MARQUEZ","FINITO","JAB","GANCHO","CINTURON","CAMPANAZO","ESQUINA","ASALTO"]),
            ("PELOTA VASCA", ["FRONTON","PALETA","MANO","REBOTE","SACADOR","RESTO","PARED","TANTO","PARTIDO","GUANTE","CANCHA","FALTA"]),
            ("TAUROMAQUIA CULTURA", ["PLAZA","CAPOTE","MULETA","TORERO","ESTOCADA","FAENA","TERCIO","MONTERA","BANDERILLAS","PASE","RUEDO","BURLADERO"]),
            ("DEPORTES OLIMPICOS MX", ["CLAVADOS","TAEKWONDO","MARCHA","TIRO","ARQUERIA","PESAS","CANOTAJE","JUDO","ESGRIMA","NATACION","CICLISMO","ATLETISMO"]),
            ("ATLETAS MEXICANOS", ["SOTOMAYOR","ESPINOZA","LIMON","MEMO","CHICHARITO","JULIO","LORENA","ALEJANDRA","PHELAN","OROZCO","ROMMEL","PAOLA"]),
            ("TERMINOS FUTBOL", ["GOLEADA","REMATE","PASE","DESMARQUE","REGATE","TIRO","PENAL","FUERAJUEGO","SAQUE","BARRIDA","ATARJETA","ARBITRO"]),
            ("TERMINOS BEISBOL", ["JONRON","PONCHE","IMPARABLE","DOBLETE","TRIPLE","BOLA","STRIKE","ROLA","ELEVADO","ROBO","CATCHER","SHORTSTOP"]),
            ("CIUDADES DEPORTE MX", ["CDMX","MONTERREY","GUADALAJARA","PUEBLA","TIJUANA","LEON","TOLUCA","QUERETARO","VERACRUZ","MERIDA","TORREON","CHIHUAHUA"]),
            ("MEDIOS DEPORTIVOS MX", ["TELEVISA","TVAZTECA","TUDN","FOXSPORTS","ESPN","RECORD","MEDIOTIEMPO","MARCA","WDEPORTES","RADIOFORMULA","CANALONCE","IMER"]),
            ("AFICION MEXICANA", ["PORRA","BOMBO","CANTO","BANDERA","HINCHA","TRIBUNA","TIFO","CLASICO","COPA","LIGUILLA","DESCENSO","ASCENSO"]),
            ("BASQUET MEXICO", ["CAPITANES","HALCONES","SOLES","PANTERAS","ABEJAS","DORADOS","MINEROS","LIBERTADORES","TRIPLES","REBOTE","TABLERO","CLAVADA"]),
            ("DEPORTES EXTREMOS", ["SURF","SKATE","PARKOUR","BMX","ESCALADA","RAPPEL","KITESURF","PARAPENTE","RAFTING","MOTOCROSS","ENDURO","TRAIL"]),
            ("PALABRAS DEPORTIVAS", ["ENTRENADOR","TACTICA","ALINEACION","SUPLENTE","CALENTAR","RECUPERAR","RITMO","POTENCIA","VELOCIDAD","RESISTENCIA","AGILIDAD","FUERZA"]),
        ],
    },
    "ES": {
        "lang": "es",
        "categories": [
            ("CLUBES LALIGA", ["MADRID","BARCA","ATLETICO","SEVILLA","BETIS","VALENCIA","VILLARREAL","REALSOCIEDAD","ATHLETIC","CELTA","GIRONA","OSASUNA"]),
            ("ESTADIOS ESPANA", ["BERNABEU","CAMPNOU","METROPOLITANO","MESTALLA","SANMAMES","VILLAMARIN","CERAMICA","BALAIDOS","SADAR","MONTILIVI","COLISEUM","RCDE"]),
            ("SELECCION ESPANA", ["ROJA","EUROCOPA","MUNDIAL","POSESION","TIKI_TAKA","CONVOCATORIA","CANTERA","CAPITAN","DEFENSA","MEDIO","ATAQUE","AFICION"]),
            ("TENIS ESPANOL", ["NADAL","ALCARAZ","MUGURUZA","FERRER","FELICIANO","ARANTXA","DAVISCUP","ARCILLA","REVES","DERECHA","SERVICIO","DEUCE"]),
            ("BALONCESTO ACB", ["REALMADRID","BARCA_BASKET","BASKONIA","VALENCIA_BC","UNICAJA","JOVENTUT","GRANCA","MURCIA","CANARIAS","OBRADOIRO","MANRESA","BREOGAN"]),
            ("TERMINOS BASKET", ["CANASTA","TRIPLE","REBOTE","ASISTENCIA","PIVOT","BASE","ALERO","BLOQUEO","CONTRAATAQUE","FALTA","TIROLIBRE","PRORROGA"]),
            ("CICLISMO ESPANA", ["VUELTA","PUERTO","PELOTON","ETAPA","CRONO","ESCALADA","SPRINT","BIDON","MALLA","DOMESTICO","ABANICO","META"]),
            ("MOTOS Y F1", ["MOTOGP","JEREZ","MONTMELO","ALONSO","SAINZ","MARTIN","MIR","MARQUEZ","POLE","BOXES","PARCFERME","PARRILLA"]),
            ("DEPORTES VASCOS", ["PELOTA","AIZKOLARI","HARRIJALE","TRAINERA","SOKATIRA","SESTARI","FRONTON","REMO","PALA","MANOMANO","ESTROPADA","REGATA"]),
            ("ATLETISMO ESPANA", ["MARCHA","VALLAS","RELEVOS","MARATON","FONDO","SALTO","PERTIGA","DISCO","JABALINA","PESO","CALLE","META"]),
            ("ATLETAS ESPANOLES", ["INDURAIN","CONTADOR","GASOL","RUDY","CALDERON","MIREIA","BELMONTE","CAROLINA","FERMIN","YULIMAR","SANDRA","RUTH"]),
            ("MEDIOS DEPORTIVOS ES", ["MARCA","AS","MUNDO","SPORT","COPE","SER","MOVISTAR","DAZN","TELEDEPORTE","LALIGATV","RTVE","ELCHIRINGUITO"]),
            ("TERMINOS FUTBOL ES", ["GOLEADOR","REGATE","PARED","DESMARQUE","CENTRO","REMATE","PENALTI","SAQUE","CORNERS","FUERAJUEGO","ARBITRO","VAR"]),
            ("COPAS Y TORNEOS", ["COPADELREY","SUPERCOPA","CHAMPIONS","EUROPA","CONFERENCE","ASCENSO","PLAYOFF","LIGA","JORNADA","DERBI","CLASICO","FINAL"]),
            ("AFICION ESPANOLA", ["PEÑA","BUFANDA","TIFO","BENGALA","GRADA","FONDO","CANTICO","ABONO","DESPLAZAMIENTO","RIVALIDAD","CELEBRACION","VICTORIA"]),
            ("DEPORTES ACUATICOS", ["NATACION","WATERPOLO","CLAVADOS","VELA","PIRAGUISMO","SURF","KITESURF","WINDSURF","REGATA","TRAVESIA","BRAZA","CRAWL"]),
            ("GIMNASIA Y COMBATE", ["TAEKWONDO","JUDO","KARATE","LUCHA","ESGRIMA","BOXEO","KICKBOXING","GRAPPLING","CATA","IPPON","PUNTO","DOJO"]),
            ("CIUDADES DEPORTE ES", ["MADRID","BARCELONA","SEVILLA","VALENCIA","BILBAO","MALAGA","VIGO","PAMPLONA","ZARAGOZA","MURCIA","ALMERIA","GIJON"]),
            ("PALABRAS ENTRENAMIENTO", ["RUTINA","SERIE","REPETICION","RECUPERACION","FUERZA","POTENCIA","RESISTENCIA","MOVILIDAD","ESTIRAR","CALENTAR","DESCANSO","PROGRESION"]),
            ("JUEGOS TRADICIONALES", ["BOLOS","PETANCA","CALVA","RANA","CHITO","PEONZA","COMBA","PAÑUELO","SOGA","TANGANA","CHAPAS","RAYUELA"]),
        ],
    },
}


def difficulty_from_index(i: int) -> int:
    if i % 10 < 4:
        return 1
    if i % 10 < 7:
        return 2
    if i % 10 < 9:
        return 3
    return 4


def generate_country(country_code: str, start_id: int, n_groups: int = 1000):
    data = COUNTRIES[country_code]
    categories = data["categories"]
    groups = []
    used = set()
    seq = start_id
    i = 0
    while len(groups) < n_groups:
        cat_name, words = categories[i % len(categories)]
        pick = tuple(sorted(random.sample(words, 4)))
        key = (cat_name, pick)
        if key not in used:
            used.add(key)
            diff = difficulty_from_index(len(groups))
            row = [str(seq), str(diff), cat_name] + list(pick)
            groups.append(row)
            seq += 1
        i += 1
        if i > 200000:
            raise RuntimeError(f"Could not generate enough unique groups for {country_code}")
    return groups, seq


def write_groups(path: Path, rows):
    with path.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write('{"' + '", "'.join(r) + '"}\n')


if __name__ == "__main__":
    out_dir = Path(r"C:\Users\robby\.openclaw\workspace\outputs\connections-sports")
    out_dir.mkdir(parents=True, exist_ok=True)

    seq = 1
    all_rows = []
    for cc in ["US", "UK", "MX", "ES"]:
        rows, seq = generate_country(cc, seq, 1000)
        all_rows.extend(rows)
        write_groups(out_dir / f"connections_sports_{cc}.txt", rows)

    write_groups(out_dir / "connections_sports_ALL_4000.txt", all_rows)
    print(str(out_dir))
